import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Super Green Plantation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <NavBar/>
        <main className="pt-14 grow ">
          {children}
        </main>

        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}